# Generated by Django 5.1.7 on 2025-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email_required', 'Email Required')], default='email_required', max_length=25)),
                ('status', models.CharField(choices=[('upcoming', 'Coming Soon'), ('publish', 'Published'), ('draft', 'Draft')], default='draft', max_length=25)),
            ],
        ),
    ]
