# Generated by Django 5.1.7 on 2025-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='If user does not have access this course.Can they see this ?'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Coming Soon'), ('publish', 'Published'), ('draft', 'Draft')], default='publish', max_length=50),
        ),
    ]
